/**
 * Nombres de tablas de Supabase usados en la app.
 * Inmutable para evitar mutaciones accidentales.
 */
export const TABLES = Object.freeze({
  companies: 'companies',
  branches: 'branches',
  categories: 'categories',
  category_branch: 'category_branch',
  products: 'products',
  product_prices: 'product_prices',
  product_branch: 'product_branch',
  orders: 'orders',
  order_items: 'order_items',
  order_payments: 'order_payments',
  order_status_history: 'order_status_history',
  payment_methods: 'payment_methods',
  clients: 'clients',
  users: 'users',
  cash_shifts: 'cash_shifts',
  cash_movements: 'cash_movements',
  cash_reconciliations: 'cash_reconciliations',
  admin_users: 'admin_users',
  admin_audit_logs: 'admin_audit_logs',
  inventory_items: 'inventory_items',
  inventory_branch: 'inventory_branch',
  hero_banners: 'hero_banners',
  plans: 'plans',
  payments_history: 'payments_history',
  onboarding_applications: 'onboarding_applications',
  onboarding_application_addons: 'onboarding_application_addons',
  addons: 'addons',
  company_addons: 'company_addons',
  plan_payment_methods: 'plan_payment_methods',
  plan_payment_method_config: 'plan_payment_method_config',
  branch_payment_methods: 'branch_payment_methods',
  tenant_connected_accounts: 'tenant_connected_accounts',
  saas_tickets: 'saas_tickets',
  saas_ticket_messages: 'saas_ticket_messages',
  saas_broadcasts: 'saas_broadcasts',
  saas_broadcast_reads: 'saas_broadcast_reads',
  saas_admin_modules: 'saas_admin_modules',
  role_definitions: 'role_definitions',
  email_log: 'email_log',
  subscription_notifications: 'subscription_notifications',
});
